# Generated by Django 2.0.1 on 2020-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名称')),
                ('user_age', models.IntegerField(verbose_name='用户年龄')),
                ('user_temperature', models.FloatField(verbose_name='用户体温')),
                ('user_address', models.CharField(max_length=128, verbose_name='用户地址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
